### ISSUE TITLE
[PEP] venezuela_national_assembly

### ISSUE THREAD

**Issue by redbonesmith** [redbonesmith/PEP#15]
* notes: Please scraper the "principle" and "suplente" entities.
* url: http://www.asambleanacional.gob.ve/diputado#1
* scraper name: venezuela_national_assembly.py

Test Cases:
* Contains given name or AKA entry, special field "name: person_name" field	WILLIAMS DANIEL DÁVILA BARRIOS
* Contains a field "tag": "political_region", where the value is given Region or Seat of Political Juristiction	Merida
* Contains a field "tag": "political_party" , where the value is given political party	Acción Democrática
* Contains a field with "tag": "url", where the value is the url of the page containing person data	http://www.asambleanacional.gob.ve/diputado/id/151
* Contains a field "tag": "picture_ul", with the value being the url of a picture on page	http://www.asambleanacional.gob.ve/uploads/diputado/dip_996ac2ec1c0b2c46c54b20303a60bf4d236132ca.jpg
* Contains given name or AKA entry, special field "name: person_name" field	ATENCIO BRITO ELY RAMÓN

**Comment by redbonesmith** [comment]
@vgomeniuk  Contains a field "tag": "political_party" , where the value is given political party Acción Democrática

Contains a field "tag": "political_region", where the value is given Region or Seat of Political Juristiction Merida

**Comment by vgomeniuk** [comment]
fixed.

**Comment by redbonesmith** [comment]
test passed @vgomeniuk
