### ISSUE TITLE
[PEP] somalia_house_of_people

### ISSUE THREAD

**Issue by redbonesmith** [redbonesmith/PEP#17]
url: http://www.parliament.gov.so/index.php/en/membersparliament-3?limitstart=0
scraper_name: somalia_house_of_people.py

# Test Cases:
* Scrape minimum number of entities	50
* Contains given name or AKA entry, special field "name: person_name" field	Yusuf Gelle Ugas
* Contains a field with "tag": "url", where the value is the url of the page containing person data	http://www.parliament.gov.so/index.php/en/xubnaha/1379-mohamed-omar-dalha-3
* Contains a field "tag": "picture_ul", with the value being the url of a picture on page	http://www.parliament.gov.so/images/profilepic.png
* Contains a field "tag": "date_of_birth", where the value is date of birth of a scraped person	2012-08-20
* Contains a field "tag": "picture_ul", with the value being the url of a picture on page	http://www.parliament.gov.so/images/Mps_Photo/Abdiladif%20Musse%20Nor.png

**Comment by vgomeniuk** [comment]
1. Following value should be stored twice or it's a mistake (Contains a field "tag": "picture_ul", with the value being the url of a picture on page)?

2. Email?

**Comment by vgomeniuk** [comment]
@redbonesmith what should I do if there is no date_of_birth? (http://www.parliament.gov.so/index.php/en/xubnaha/1395-zakarie-hussein-arreh-2)

FYI, there is plenty of other info.

**Comment by redbonesmith** [comment]
@vgomeniuk  *date_of_birth*

**Comment by redbonesmith** [comment]
@vgomeniuk  about picture_url : test will search all provided picture_url values from test suite (so it will search first img, then second one)

**Comment by vgomeniuk** [comment]
ready

**Comment by redbonesmith** [comment]
@vgomeniuk OK
