### ISSUE TITLE
[PEP] guyana_national_assembly

### ISSUE THREAD

**Issue by redbonesmith** [redbonesmith/PEP#19]
*URL*:	http://parliament.gov.gy/about-parliament/who-in-parliament/
*Notes*:	In addition to the URL please scrape: http://parliament.gov.gy/about-parliament/parliamentarian/

Rule Name	Rule Value
* Contains given name or AKA entry, special field "name: person_name" field	Ashni K. Singh
* Contains a field "tag": "political_party" , where the value is given political party	People Progressive Party/Civic
* Contains a field with "tag": "url", where the value is the url of the page containing person data	http://parliament.gov.gy/about-parliament/parliamentarian/david-granger/
* Contains a field "tag": "picture_ul", with the value being the url of a picture on page	http://parliament.gov.gy/images/member_photos/87/robert__small.jpg
* Contains a field "tag": "political_position", where value is given political position	Minister of Home Affairs
* Contains a field "tag": "political_position", where value is given political position	Speaker of the House
* Contains given name or AKA entry, special field "name: person_name" field	Robert M. Persaud
* Contains a field with "tag": "url", where the value is the url of the page containing person data	http://parliament.gov.gy/about-parliament/parliamentarian/dr-veersammy-ramayya/
* Contains a field "tag": "political_party" , where the value is given political party	Alliance for Change - AFC -
* Contains a field "tag": "picture_ul", with the value being the url of a picture on page	http://parliament.gov.gy/images/member_photos/139/ganga_persaud__small.jpg
* Contains any field with the given text	A young Attorney at Law James Bond is a first time member of the National Assembly with opposition responsibility for Legal Affairs which includes constitution reform; public law; justice improvement; criminal justice system; legal aid and labour relati
* Contains any field with the given text	A Microbiologist, DrRamsammy has served in the National Assembly since 1992. The former Senior Min. of Health, Dr. Ramsammy now holds the Portfolio of Minister of Agriculture with the responsibility for Fisheries, Livestock, Other Crops, Agro-energy, Drai

**Comment by vgomeniuk** [comment]
@redbonesmith ready.

**Comment by redbonesmith** [comment]
ok
